# Elasticsearch Dockerfile

# Use an official Elasticsearch image as base
FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.2

# Set environment variables
ENV discovery.type=single-node
# ENV xpack.security.enabled=false

# Expose port
EXPOSE 9200
