# Kibana Dockerfile

# Use an official Kibana image as base
FROM docker.elastic.co/kibana/kibana:7.10.2

# # Set environment variable for Elasticsearch URL
# ENV ELASTICSEARCH_URL=http://elastics-search.railway.internal:9200


# Expose port
EXPOSE 5601
