# Use an official Elasticsearch image as base
FROM docker.elastic.co/elasticsearch/elasticsearch:7.10.2

# Install Tini
USER root
RUN apt-get update && apt-get install -y tini && apt-get clean

# Set environment variables
ENV discovery.type=single-node
ENV xpack.security.enabled=false

# Expose port
EXPOSE 9200

# Use Tini as the entry point
ENTRYPOINT ["/usr/bin/tini", "--"]

# Set the command to start Elasticsearch
CMD ["bin/elasticsearch"]
