# version: "3.1"

# services:
#   elasticssearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#     ports:
#       - 9200:9200
#     volumes:
#       - elasticsearch-data:/usr/share/elasticsearch/data
#     networks:
#       - elk

#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.10.2
#     container_name: kibana
#     depends_on:
#       - elasticssearch
#     ports:
#       - 5601:5601
#     networks:
#       - elk
#     # environment:
#     #   - ELASTICSEARCH_URL=http://elasticsearch:9200

# networks:
#   elk:
#     driver: bridge

# volumes:
#   elasticsearch-data:
#     driver: local
